name: console-conf
base: core22
summary: console-conf Ubuntu Core first boot experience
description: |
  console-conf provide device onboarding experience for
  Ubuntu Core systems. User can configure network and
  assume ownership of the system.

grade: stable
confinement: strict

build-packages:
  - apt-utils
  - devscripts
  - debhelper-compat
  - dh-python
  - fakeroot
  - iso-codes
  - libnl-genl-3-dev
  - libnl-route-3-dev
  - pkg-config
  - python3
  - python3-all-dev
  - python3-attr
  - python3-coverage
  - python3-distutils-extra
  - python3-flake8
  - python3-jsonschema
  - python3-mock
  - python3-nose
  - python3-pyudev
  - python3-setuptools
  - python3-testtools
  - python3-yaml
